services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    # image: react-flask-app-api
    depends_on:
      - postgres
    ports:
      - "5010:5000"
    links:
      - postgres:postgres
    networks:
      - robotics_backend
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.client
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:80"
  #   links:
  #     - backend:backend
  #   networks:
  #     - robotics_backend
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - robotics_backend
networks:
  robotics_backend:
    driver: bridge